openapi: 3.0.0
info:
  title: API de gestion des messages des étudiants
  version: 1.0.0
  description: API permettant la gestion des messages des étudiants avec MongoDB et Servlets.
paths:
  /messages/{num}:
    post:
      summary: Ajouter un message
      description: Ajoute un message non lu de texte fourni dans le body pour un étudiant donné.
      parameters:
        - name: num
          in: path
          required: true
          description: Numéro de l'étudiant
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Contenu du message
      responses:
        201:
          description: Message créé avec succès
        400:
          description: Requête invalide
      security:
        - systemAuth: []
    get:
      summary: Récupérer les messages d'un étudiant
      description: Retourne un tableau des messages pour un étudiant donné.
      parameters:
        - name: num
          in: path
          required: true
          description: Numéro de l'étudiant
          schema:
            type: integer
      responses:
        200:
          description: Liste des messages récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    text:
                      type: string
                    lu:
                      type: boolean
        401:
          description: Non autorisé
      security:
        - studentAuth: []
  /messages/{idMessage}:
    put:
      summary: Marquer un message comme lu
      description: Modifie le message d'ObjectId `idMessage` en mettant `lu` à `true`.
      parameters:
        - name: idMessage
          in: path
          required: true
          description: Identifiant du message
          schema:
            type: string
      responses:
        200:
          description: Message marqué comme lu
        404:
          description: Message non trouvé
    delete:
      summary: Supprimer un message
      description: Supprime un message donné si l'étudiant est autorisé.
      parameters:
        - name: idMessage
          in: path
          required: true
          description: Identifiant du message
          schema:
            type: string
      responses:
        200:
          description: Message supprimé avec succès
        401:
          description: Non autorisé
        404:
          description: Message non trouvé
      security:
        - studentAuth: []
components:
  securitySchemes:
    systemAuth:
      type: http
      scheme: bearer
      description: Authentification pour le système (ex. Bearer Token)
    studentAuth:
      type: http
      scheme: bearer
      description: Authentification pour les étudiants (ex. Bearer Token)
